---
openshift_cluster_content:
- object: Build Uncontained Prototype
  content:
  - name: Create Projects
    file: "{{ inventory_dir }}/../.openshift/files/projects.yml"
    file_action: create
    tags:
      - development
  - name: Build Builder Image
    file: "{{ inventory_dir }}/../.openshift/files/builder-image.yml"
    namespace: uncontained--prototype
    tags:
      - prototype
  - name: Hugo build
    file: "{{ inventory_dir }}/../.openshift/files/hugo-build.yml"
    namespace: uncontained--prototype
    tags:
      - prototype
  - name: Site build
    file: "{{ inventory_dir }}/../.openshift/files/site-build.yml"
    namespace: uncontained--prototype
    tags:
      - prototype
  - name: Deployment - prototype
    file: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    namespace: uncontained--prototype
    tags:
      - prototype
