apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    build: site
  name: site
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: site:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    images:
    - from:
        kind: ImageStreamTag
        name: uncontainedio:latest
        namespace: uncontained--prototype
      paths:
      - destinationDir: .
        sourcePath: /opt/app-root/src/
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
