apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: site
  name: site
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: site:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: container-images/nginx/Dockerfile
      from:
        kind: ImageStreamTag
        name: rhel7-platops-nginx:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: M3kDodiUUTor4_8WUThv
    type: GitHub
  - generic:
      secret: TOv-GBI9XL536JJ29vdQ
    type: Generic
status:
  lastVersion: 0
